"""Small-model robustness: vector_search tool must accept filenames given as a
single string (not just a JSON array).

Observed on gpt-oss-20b served by vLLM: when only one filename is relevant, the
model emits `"filenames": "foo.md"` instead of `"filenames": ["foo.md"]`. The
Pydantic schema generated by `@function_tool` from `filenames: list[str] | None`
then rejects the call with a `list_type` validation error, and the tool never
runs — silently degrading search quality.
"""

from __future__ import annotations

import json

import pytest
from agents.tool_context import ToolContext

from src.agents import vector_search_tool
from src.agents.vector_search_tool import vector_search


def _tool_context() -> ToolContext:
    return ToolContext(
        context=None,
        tool_name="vector_search",
        tool_call_id="test-call",
        tool_arguments="",
    )


@pytest.mark.asyncio
async def test_vector_search_accepts_string_filenames_and_coerces_to_list(monkeypatch):
    """RED first: the current schema rejects str filenames. After the fix, the
    tool accepts the string and the underlying impl receives a single-item list.
    """
    captured: dict = {}

    async def _fake_impl(**kwargs):
        captured.update(kwargs)
        return {"hits": []}

    monkeypatch.setattr(vector_search_tool, "vector_search_impl", _fake_impl)

    args = json.dumps({"query": "mips vs rewoo", "filenames": "LLM_Autonomous_Agents.md"})

    await vector_search.on_invoke_tool(_tool_context(), args)

    assert captured.get("filenames") == ["LLM_Autonomous_Agents.md"], (
        f"Expected single-item list coercion, got {captured.get('filenames')!r}"
    )
    assert captured.get("query") == "mips vs rewoo"


@pytest.mark.asyncio
async def test_vector_search_still_accepts_list_filenames(monkeypatch):
    """Regression guard: the canonical list[str] input must keep working."""
    captured: dict = {}

    async def _fake_impl(**kwargs):
        captured.update(kwargs)
        return {"hits": []}

    monkeypatch.setattr(vector_search_tool, "vector_search_impl", _fake_impl)

    args = json.dumps({"query": "q", "filenames": ["a.md", "b.md"]})

    await vector_search.on_invoke_tool(_tool_context(), args)

    assert captured.get("filenames") == ["a.md", "b.md"]


@pytest.mark.asyncio
async def test_vector_search_accepts_missing_filenames(monkeypatch):
    """Optional filenames must stay optional — call with no filenames at all."""
    captured: dict = {}

    async def _fake_impl(**kwargs):
        captured.update(kwargs)
        return {"hits": []}

    monkeypatch.setattr(vector_search_tool, "vector_search_impl", _fake_impl)

    args = json.dumps({"query": "q"})

    await vector_search.on_invoke_tool(_tool_context(), args)

    assert captured.get("filenames") in (None, [])


@pytest.mark.asyncio
async def test_vector_search_coerces_empty_string_filenames_to_none_or_empty(monkeypatch):
    """An empty string for filenames should not become [""] — it must be
    treated as "no filter" (None or empty list)."""
    captured: dict = {}

    async def _fake_impl(**kwargs):
        captured.update(kwargs)
        return {"hits": []}

    monkeypatch.setattr(vector_search_tool, "vector_search_impl", _fake_impl)

    args = json.dumps({"query": "q", "filenames": ""})

    await vector_search.on_invoke_tool(_tool_context(), args)

    assert captured.get("filenames") in (None, []), (
        f"Empty string must not become [''], got {captured.get('filenames')!r}"
    )
